CREATE DATABASE homeharvest;

CREATE TABLE IF NOT EXISTS sold (
    property_url VARCHAR(255),
    mls VARCHAR(10),
    mls_id VARCHAR(50),
    status VARCHAR(20),
    style VARCHAR(50),
    street VARCHAR(255),
    unit VARCHAR(50),
    city VARCHAR(20),
    state VARCHAR(10),
    zip_code VARCHAR(10),
    beds SMALLINT,
    full_baths SMALLINT,
    half_baths SMALLINT,
    sqft INTEGER,
    year_built INTEGER,
    days_on_mls SMALLINT,
    list_price INTEGER,
    list_date DATE,
    sold_price INTEGER,
    last_sold_date DATE,
    lot_sqft INTEGER,
    price_per_sqft INTEGER,
    latitude REAL,
    longitude REAL,
    stories INTEGER,
    hoa_fee SMALLINT,
    parking_garage SMALLINT,
    primary_photo VARCHAR(255),
    alt_photos TEXT,
    UNIQUE NULLS NOT DISTINCT (property_url, mls_id)
);

CREATE TABLE IF NOT EXISTS selling (
    property_url VARCHAR(255),
    mls VARCHAR(10),
    mls_id VARCHAR(50),
    status VARCHAR(20),
    style VARCHAR(50),
    street VARCHAR(255),
    unit VARCHAR(50),
    city VARCHAR(20),
    state VARCHAR(10),
    zip_code VARCHAR(10),
    beds SMALLINT,
    full_baths SMALLINT,
    half_baths SMALLINT,
    sqft INTEGER,
    year_built INTEGER,
    days_on_mls SMALLINT,
    list_price INTEGER,
    list_date DATE,
    sold_price INTEGER,
    last_sold_date DATE,
    lot_sqft INTEGER,
    price_per_sqft INTEGER,
    latitude REAL,
    longitude REAL,
    stories INTEGER,
    hoa_fee SMALLINT,
    parking_garage SMALLINT,
    primary_photo VARCHAR(255),
    alt_photos TEXT,
    UNIQUE NULLS NOT DISTINCT (property_url, mls_id)
);

CREATE TABLE IF NOT EXISTS renting (
    property_url VARCHAR(255),
    mls VARCHAR(10),
    mls_id VARCHAR(50),
    status VARCHAR(20),
    style VARCHAR(50),
    street VARCHAR(255),
    unit VARCHAR(50),
    city VARCHAR(20),
    state VARCHAR(10),
    zip_code VARCHAR(10),
    beds SMALLINT,
    full_baths SMALLINT,
    half_baths SMALLINT,
    sqft INTEGER,
    year_built INTEGER,
    days_on_mls SMALLINT,
    list_price INTEGER,
    list_date DATE,
    sold_price INTEGER,
    last_sold_date DATE,
    lot_sqft INTEGER,
    price_per_sqft INTEGER,
    latitude REAL,
    longitude REAL,
    stories INTEGER,
    hoa_fee SMALLINT,
    parking_garage SMALLINT,
    primary_photo VARCHAR(255),
    alt_photos TEXT,
    UNIQUE NULLS NOT DISTINCT (property_url, mls_id)
);

CREATE TABLE IF NOT EXISTS pending (
    property_url VARCHAR(255),
    mls VARCHAR(10),
    mls_id VARCHAR(50),
    status VARCHAR(20),
    style VARCHAR(50),
    street VARCHAR(255),
    unit VARCHAR(50),
    city VARCHAR(20),
    state VARCHAR(10),
    zip_code VARCHAR(10),
    beds SMALLINT,
    full_baths SMALLINT,
    half_baths SMALLINT,
    sqft INTEGER,
    year_built INTEGER,
    days_on_mls SMALLINT,
    list_price INTEGER,
    list_date DATE,
    sold_price INTEGER,
    last_sold_date DATE,
    lot_sqft INTEGER,
    price_per_sqft INTEGER,
    latitude REAL,
    longitude REAL,
    stories INTEGER,
    hoa_fee SMALLINT,
    parking_garage SMALLINT,
    primary_photo VARCHAR(255),
    alt_photos TEXT,
    UNIQUE NULLS NOT DISTINCT (property_url, mls_id)
);
